import '../core/chatty_activity_moment.dart';
import '../core/game_state.dart';
import '../core/grid.dart';
import '../core/item_template.dart';
import '../core/pet_rules.dart';
import '../core/pet_state.dart';

class StarterDatapack {
  static const templates = <String, ItemTemplate>{
    'strawberry': ItemTemplate(
      id: 'strawberry',
      displayName: 'Strawberry',
      emoji: '🍓',
      kind: ItemKind.food,
      fullnessDelta: 2,
      affectionDelta: 1,
      inspectLines: ['Oh! Strawberry!', 'Berry snack!', 'Red treat for Chatty?'],
      useLines: [
        'Chatty munches the strawberry.',
        'Sweet berry time!',
        'Nom nom, berry gone!',
      ],
      noticeLines: [
        'Oh! Strawberry!',
        'Chatty spots a berry.',
        'Berry on the stage!',
      ],
    ),
    'ball': ItemTemplate(
      id: 'ball',
      displayName: 'Ball',
      emoji: '⚽',
      kind: ItemKind.toy,
      funDelta: 2,
      affectionDelta: 1,
      inspectLines: ['Round thing!', 'Ball means zoomies.', 'Bouncy play time?'],
      useLines: [
        'Chatty bats the ball around!',
        'Play play play!',
        'The ball gets a happy bonk.',
      ],
      noticeLines: [
        'Ball on the stage!',
        'Chatty notices the ball.',
        'A ball for playtime!',
      ],
    ),
    'sock': ItemTemplate(
      id: 'sock',
      displayName: 'Sock',
      emoji: '🧦',
      kind: ItemKind.comfort,
      restDelta: 1,
      inspectLines: [
        'Sock smells funny.',
        'Soft, but a little silly.',
        'Sock is not a snack.',
      ],
      useLines: [
        'Chatty flops near the sock.',
        'Comfy sock corner.',
        'Chatty sniffs the sock and settles down.',
      ],
      noticeLines: [
        'A sock appeared.',
        'Chatty found a cozy sock.',
        'Sock on the floor!',
      ],
    ),
    'shiny_rock': ItemTemplate(
      id: 'shiny_rock',
      displayName: 'Shiny Rock',
      emoji: '💎',
      kind: ItemKind.curiosity,
      affectionDelta: 1,
      inspectLines: [
        'Shiny rock!',
        'Sparkly little treasure.',
        'Chatty squints at the rock.',
      ],
      useLines: [
        'Chatty keeps looking.',
        'Sparkle stare activated.',
        'Chatty studies every glittery angle.',
      ],
      noticeLines: [
        'Something shiny!',
        'Chatty notices a bright rock.',
        'A tiny sparkle catches Chatty\'s eye.',
      ],
    ),
    'apple_slices': ItemTemplate(
      id: 'apple_slices',
      displayName: 'Apple Slices',
      emoji: '🍎',
      kind: ItemKind.food,
      fullnessDelta: 2,
      affectionDelta: 1,
      unlockLevel: 4,
      inspectLines: [
        'Little apple moons.',
        'Crunchy slice snack.',
        'Chatty sniffs the apple pieces.',
      ],
      useLines: [
        'Crunch crunch, apple gone.',
        'Chatty nibbles the apple slices.',
        'Apple snack success!',
      ],
      noticeLines: [
        'Apple slices for Chatty!',
        'A crisp snack appears.',
        'Chatty notices sweet apple pieces.',
      ],
    ),
    'cushion': ItemTemplate(
      id: 'cushion',
      displayName: 'Cushion',
      emoji: '🛋️',
      kind: ItemKind.restItem,
      restDelta: 2,
      affectionDelta: 1,
      unlockLevel: 4,
      inspectLines: [
        'Soft cushion!',
        'This looks nap-shaped.',
        'A good place for a flop.',
      ],
      useLines: [
        'Chatty settles onto the cushion.',
        'Tiny nap mode.',
        'Cushion cuddles for Chatty.',
      ],
      noticeLines: [
        'A cushion is waiting.',
        'Chatty notices a comfy spot.',
        'That cushion looks cozy.',
      ],
    ),
    'brush': ItemTemplate(
      id: 'brush',
      displayName: 'Brush',
      emoji: '🪮',
      kind: ItemKind.cleanItem,
      cleanlinessDelta: 2,
      affectionDelta: 1,
      unlockLevel: 4,
      inspectLines: [
        'Brushy brush.',
        'This could fix the fluff.',
        'Neat fur tool spotted.',
      ],
      useLines: [
        'Chatty gets a gentle brushing.',
        'Fresh and tidy!',
        'The fluff looks much neater now.',
      ],
      noticeLines: [
        'A brush appears.',
        'Chatty notices the brush.',
        'Brush means tidy time.',
      ],
    ),
    'shell': ItemTemplate(
      id: 'shell',
      displayName: 'Shell',
      emoji: '🐚',
      kind: ItemKind.curiosity,
      affectionDelta: 1,
      unlockLevel: 4,
      inspectLines: [
        'A swirly shell!',
        'Tiny ocean treasure.',
        'Chatty listens to the shell very seriously.',
      ],
      useLines: [
        'Chatty tilts the shell back and forth.',
        'Shell staring time.',
        'The shell gets a careful little sniff.',
      ],
      noticeLines: [
        'A shell rolls into view.',
        'Chatty spots a swirly shell.',
        'Something beachy is on the stage.',
      ],
    ),
    'biscuit': ItemTemplate(
      id: 'biscuit',
      displayName: 'Biscuit',
      emoji: '🦴',
      kind: ItemKind.food,
      fullnessDelta: 3,
      affectionDelta: 1,
      unlockLevel: 8,
      inspectLines: [
        'Biscuit! Biscuit!',
        'This one smells extra exciting.',
        'Crunchy reward spotted.',
      ],
      useLines: [
        'Chatty chomps the biscuit happily.',
        'That biscuit disappears fast.',
        'Crunch crunch, all gone!',
      ],
      noticeLines: [
        'A biscuit appears!',
        'Chatty notices the crunchy treat.',
        'Reward snack on the stage!',
      ],
    ),
    'bubble_wand': ItemTemplate(
      id: 'bubble_wand',
      displayName: 'Bubble Wand',
      emoji: '🪄',
      kind: ItemKind.toy,
      funDelta: 3,
      affectionDelta: 1,
      unlockLevel: 8,
      inspectLines: [
        'Bubble time?',
        'A wand for floaty circles.',
        'Chatty watches for the first bubble.',
      ],
      useLines: [
        'Chatty snaps at pretend bubbles.',
        'Bubble chase activated!',
        'Floaty fun fills the room.',
      ],
      noticeLines: [
        'A bubble wand sparkles nearby.',
        'Chatty notices the bubble wand.',
        'Something playful and floaty appears.',
      ],
    ),
    'blanket': ItemTemplate(
      id: 'blanket',
      displayName: 'Blanket',
      emoji: '🧺',
      kind: ItemKind.restItem,
      restDelta: 3,
      affectionDelta: 1,
      unlockLevel: 8,
      inspectLines: [
        'Big cozy blanket.',
        'This looks extra snuggly.',
        'Chatty wants to burrow.',
      ],
      useLines: [
        'Chatty burrows under the blanket.',
        'Blanket nap success.',
        'Only a tiny cozy snoot sticks out.',
      ],
      noticeLines: [
        'A blanket lands softly.',
        'Chatty notices the soft blanket.',
        'Cozy fabric on the stage!',
      ],
    ),
    'storybook': ItemTemplate(
      id: 'storybook',
      displayName: 'Storybook',
      emoji: '📖',
      kind: ItemKind.comfort,
      restDelta: 1,
      affectionDelta: 2,
      unlockLevel: 8,
      inspectLines: [
        'A bedtime story?',
        'Pages full of tiny adventures.',
        'Chatty stares at the pictures.',
      ],
      useLines: [
        'Chatty listens to a cozy little tale.',
        'Story time makes the room feel calm.',
        'Chatty sits very still for the good part.',
      ],
      noticeLines: [
        'A storybook opens nearby.',
        'Chatty notices the storybook.',
        'There is a cozy book on the stage.',
      ],
    ),
    'carrot': ItemTemplate(
      id: 'carrot',
      displayName: 'Carrot',
      emoji: '🥕',
      kind: ItemKind.food,
      fullnessDelta: 2,
      cleanlinessDelta: 1,
      affectionDelta: 1,
      unlockLevel: 12,
      inspectLines: [
        'Crunchy orange snack.',
        'Carrot stick for Chatty?',
        'Chatty gives the carrot a hopeful look.',
      ],
      useLines: [
        'Chatty cronches the carrot.',
        'That was a crisp little snack.',
        'Orange snack mission complete.',
      ],
      noticeLines: [
        'A carrot appears.',
        'Chatty spots a crunchy carrot.',
        'Bright orange snack on the stage!',
      ],
    ),
    'squeaky_duck': ItemTemplate(
      id: 'squeaky_duck',
      displayName: 'Squeaky Duck',
      emoji: '🦆',
      kind: ItemKind.toy,
      funDelta: 3,
      affectionDelta: 1,
      unlockLevel: 12,
      inspectLines: [
        'It squeaks!',
        'A duck made for silly sounds.',
        'Chatty cocks one ear at the duck.',
      ],
      useLines: [
        'Squeak squeak, zoom zoom!',
        'Chatty boops the duck with delight.',
        'The duck gets a very serious squeak test.',
      ],
      noticeLines: [
        'A squeaky duck pops in.',
        'Chatty notices the silly duck.',
        'A cheerful duck is on the stage.',
      ],
    ),
    'moon_pillow': ItemTemplate(
      id: 'moon_pillow',
      displayName: 'Moon Pillow',
      emoji: '🌙',
      kind: ItemKind.restItem,
      restDelta: 3,
      affectionDelta: 2,
      unlockLevel: 12,
      inspectLines: [
        'Moon-shaped pillow!',
        'This one looks extra dreamy.',
        'Chatty studies the sleepy moon curve.',
      ],
      useLines: [
        'Chatty curls around the moon pillow.',
        'Dreamy cozy mode begins.',
        'The moon pillow gets a perfect sleepy flop.',
      ],
      noticeLines: [
        'A moon pillow appears.',
        'Chatty notices the dreamy pillow.',
        'Something soft and sleepy is nearby.',
      ],
    ),
    'bath_bucket': ItemTemplate(
      id: 'bath_bucket',
      displayName: 'Bath Bucket',
      emoji: '🪣',
      kind: ItemKind.cleanItem,
      cleanlinessDelta: 3,
      affectionDelta: 1,
      unlockLevel: 12,
      inspectLines: [
        'Splash bucket.',
        'That looks like tidy-up time.',
        'Chatty peeks into the little bath bucket.',
      ],
      useLines: [
        'Chatty gets a careful splash-and-scrub.',
        'Clean paws, clean fluff.',
        'Bath bucket duty complete.',
      ],
      noticeLines: [
        'A bath bucket appears.',
        'Chatty notices the tidy bucket.',
        'A splashy clean-up tool arrives.',
      ],
    ),
    'star_lamp': ItemTemplate(
      id: 'star_lamp',
      displayName: 'Star Lamp',
      emoji: '🌟',
      kind: ItemKind.comfort,
      restDelta: 1,
      affectionDelta: 2,
      unlockLevel: 16,
      inspectLines: [
        'Tiny starlight lamp.',
        'Soft glow for a calm room.',
        'Chatty watches the warm little light.',
      ],
      useLines: [
        'The star lamp makes everything feel gentler.',
        'Chatty settles under the starry glow.',
        'A warm light twinkles over the stage.',
      ],
      noticeLines: [
        'A star lamp begins to glow.',
        'Chatty notices the tiny light.',
        'A warm starry sparkle appears.',
      ],
    ),
    'music_box': ItemTemplate(
      id: 'music_box',
      displayName: 'Music Box',
      emoji: '🎵',
      kind: ItemKind.comfort,
      funDelta: 1,
      restDelta: 1,
      affectionDelta: 2,
      unlockLevel: 16,
      inspectLines: [
        'A tiny tune box.',
        'It looks ready for a lullaby.',
        'Chatty waits for the first note.',
      ],
      useLines: [
        'A gentle tune fills the room.',
        'Chatty sways to the little melody.',
        'Music box time makes everything softer.',
      ],
      noticeLines: [
        'A music box appears.',
        'Chatty notices the tiny tune box.',
        'Something musical lands nearby.',
      ],
    ),
    'berry_bowl': ItemTemplate(
      id: 'berry_bowl',
      displayName: 'Berry Bowl',
      emoji: '🫐',
      kind: ItemKind.food,
      fullnessDelta: 3,
      affectionDelta: 2,
      unlockLevel: 16,
      inspectLines: [
        'A whole bowl of berries!',
        'That snack looks deluxe.',
        'Chatty noses the berry bowl eagerly.',
      ],
      useLines: [
        'Chatty enjoys a fancy berry feast.',
        'Berry bowl gone, happy tummy achieved.',
        'Snack bowl success for Chatty.',
      ],
      noticeLines: [
        'A berry bowl appears.',
        'Chatty notices the special snack.',
        'Fancy berries on the stage!',
      ],
    ),
    'kite': ItemTemplate(
      id: 'kite',
      displayName: 'Kite',
      emoji: '🪁',
      kind: ItemKind.toy,
      funDelta: 3,
      affectionDelta: 2,
      unlockLevel: 16,
      inspectLines: [
        'A bright little kite.',
        'That looks like breezy fun.',
        'Chatty tracks every colorful corner.',
      ],
      useLines: [
        'Chatty imagines a giant kite chase.',
        'Breezy playtime fills Chatty with zoomies.',
        'The kite inspires a very happy wiggle.',
      ],
      noticeLines: [
        'A colorful kite appears.',
        'Chatty notices the bright kite.',
        'Something fluttery lands on the stage.',
      ],
    ),
  };

  static GameState newGame() {
    return GameState(
      gridWidth: 6,
      gridHeight: 5,
      pet: const PetState(
        id: 'chatty',
        name: 'Chatty',
        position: GridCoord(2, 2),
        mood: PetMood.curious,
      ),
      templates: templates,
      items: const [],
      tickCount: 0,
      dayCount: 1,
      timeOfDay: TimeOfDay.morning,
      eventLog: const [],
      recentLines: const [],
      unlockedTemplateIds: {'strawberry', 'ball', 'sock', 'shiny_rock'},
      activityMoment: const ChattyActivityMoment(
        serial: 0,
        scene: ChattyScene.idle,
        phase: SkyPhase.morning,
        caption: 'Chatty is awake and ready to play!',
        effectEmoji: '☀️',
      ),
    );
  }
}
